package clusteradopt

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ingresslabs/ktl/internal/stack"
	"gopkg.in/yaml.v3"
	"helm.sh/helm/v3/pkg/chart"
)

func TestRenderStackYAMLFromSnapshot(t *testing.T) {
	snapshot := &Snapshot{
		Cluster: ClusterInfo{Name: "dev", Context: "dev"},
		Namespaces: []NamespaceInfo{
			{Name: "apps"},
			{Name: "platform"},
		},
		HelmReleases: []HelmRelease{
			{
				Name:         "api",
				Namespace:    "apps",
				Chart:        "api-chart",
				ChartVersion: "1.2.3",
				Status:       "deployed",
				Values: map[string]any{
					"replicaCount": 2,
				},
				ChartObject: &chart.Chart{
					Metadata: &chart.Metadata{Name: "api-chart", Version: "1.2.3"},
				},
			},
			{
				Name:         "redis",
				Namespace:    "platform",
				Chart:        "redis",
				ChartVersion: "20.1.0",
				Status:       "failed",
			},
		},
		GitOps: []GitOpsObject{
			{System: "argocd", Kind: "Application", Namespace: "argocd", Name: "api", Source: "https://git.example.com/app deploy/api", Destination: "apps"},
		},
		Workloads: []Workload{
			{Kind: "Deployment", Namespace: "apps", Name: "api", ManagedBy: "Helm", HelmRelease: "api"},
			{Kind: "Deployment", Namespace: "apps", Name: "worker", ManagedBy: "manual"},
		},
		Helmfiles: []string{"./helmfile.yaml"},
	}

	raw, values, charts, err := RenderStackYAML(snapshot, RenderOptions{
		StackName:   "adopted-dev",
		ClusterName: "dev",
		Context:     "dev",
		ChartsDir:   "charts/imported",
		WriteCharts: true,
		ValuesDir:   "values/imported",
		WriteValues: true,
	})
	if err != nil {
		t.Fatalf("render stack: %v", err)
	}
	for _, want := range []string{
		"Generated by `ktl init from-cluster`",
		"GitOps resources found",
		"Non-Helm workloads found",
		"chart: ./charts/imported/apps/api-chart-1.2.3.tgz",
		"chartVersion: 1.2.3",
		"values/imported/apps/api.yaml",
		"status:failed",
	} {
		if !strings.Contains(raw, want) {
			t.Fatalf("expected rendered stack to contain %q, got:\n%s", want, raw)
		}
	}
	if len(values) != 1 {
		t.Fatalf("expected one values file, got %d", len(values))
	}
	if values[0].Path != "values/imported/apps/api.yaml" {
		t.Fatalf("unexpected values path %q", values[0].Path)
	}
	if len(charts) != 1 {
		t.Fatalf("expected one chart file, got %d", len(charts))
	}
	if charts[0].Path != "charts/imported/apps/api-chart-1.2.3.tgz" {
		t.Fatalf("unexpected chart path %q", charts[0].Path)
	}

	var parsed stack.StackFile
	if err := yaml.Unmarshal([]byte(raw), &parsed); err != nil {
		t.Fatalf("parse rendered stack yaml: %v", err)
	}
	if parsed.Name != "adopted-dev" {
		t.Fatalf("expected stack name adopted-dev, got %q", parsed.Name)
	}
	if len(parsed.Releases) != 2 {
		t.Fatalf("expected two releases, got %d", len(parsed.Releases))
	}

	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "stack.yaml"), []byte(raw), 0o644); err != nil {
		t.Fatalf("write stack.yaml: %v", err)
	}
	u, err := stack.Discover(root)
	if err != nil {
		t.Fatalf("discover generated stack: %v", err)
	}
	if _, err := stack.Compile(u, stack.CompileOptions{}); err != nil {
		t.Fatalf("compile generated stack: %v", err)
	}
}

func TestWriteValuesFiles(t *testing.T) {
	root := t.TempDir()
	files := []ValuesFile{
		{Path: "values/adopted/apps/api.yaml", Values: map[string]any{"replicaCount": 2}},
	}
	res, err := WriteValuesFiles(root, files, false, false)
	if err != nil {
		t.Fatalf("write values: %v", err)
	}
	if len(res.Created) != 1 || res.Created[0] != "values/adopted/apps/api.yaml" {
		t.Fatalf("unexpected created files: %#v", res.Created)
	}
	raw, err := os.ReadFile(filepath.Join(root, "values", "adopted", "apps", "api.yaml"))
	if err != nil {
		t.Fatalf("read values: %v", err)
	}
	if !strings.Contains(string(raw), "replicaCount: 2") {
		t.Fatalf("unexpected values content:\n%s", raw)
	}

	res, err = WriteValuesFiles(root, files, false, false)
	if err != nil {
		t.Fatalf("rewrite values: %v", err)
	}
	if len(res.Skipped) != 1 {
		t.Fatalf("expected skip on existing file, got %#v", res)
	}
}

func TestWriteChartFiles(t *testing.T) {
	root := t.TempDir()
	files := []ChartFile{
		{Path: "charts/adopted/apps/api-1.2.3.tgz", Chart: &chart.Chart{Metadata: &chart.Metadata{APIVersion: "v2", Name: "api", Version: "1.2.3"}}},
	}
	res, err := WriteChartFiles(root, files, false, false)
	if err != nil {
		t.Fatalf("write charts: %v", err)
	}
	if len(res.Created) != 1 || res.Created[0] != "charts/adopted/apps/api-1.2.3.tgz" {
		t.Fatalf("unexpected created charts: %#v", res.Created)
	}
	if _, err := os.Stat(filepath.Join(root, "charts", "adopted", "apps", "api-1.2.3.tgz")); err != nil {
		t.Fatalf("expected chart archive: %v", err)
	}
	res, err = WriteChartFiles(root, files, false, false)
	if err != nil {
		t.Fatalf("rewrite charts: %v", err)
	}
	if len(res.Skipped) != 1 {
		t.Fatalf("expected skip on existing chart, got %#v", res)
	}
}

func TestDiscoverHelmfiles(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "helmfile.yaml"), []byte("releases: []\n"), 0o644); err != nil {
		t.Fatalf("write helmfile: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(root, "services", "api"), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "services", "api", "helmfile.yml"), []byte("releases: []\n"), 0o644); err != nil {
		t.Fatalf("write nested helmfile: %v", err)
	}
	got := DiscoverHelmfiles(root)
	want := []string{"./helmfile.yaml", "./services/api/helmfile.yml"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("expected %v, got %v", want, got)
	}
}
